export type PressCategory =
  | "Profile"
  | "Television"
  | "Newspaper"
  | "Magazine"
  | "Interview"
  | "Speaker Profile"
  | "International"
  | "Award"
  | "Event"
  | "Legacy Archive";

export type PressRegion =
  | "India"
  | "Global"
  | "China"
  | "Nepal"
  | "Finland"
  | "Thailand"
  | "Bhutan"
  | "Singapore"
  | "UAE"
  | "UK";

export type PressStoryType =
  | "Newspaper"
  | "Magazine"
  | "TV"
  | "Interview"
  | "Event"
  | "Award"
  | "International";

export type PressStory = {
  id: string;
  title: string;
  outlet: string;
  publisher: string;
  category: PressCategory;
  type: PressStoryType;
  region: PressRegion;
  country: PressRegion;
  year?: string;
  eyebrow: string;
  summary: string;
  image: string;
  alt: string;
  url?: string;
  sourceType:
    | "External Profile"
    | "Legacy Website"
    | "Press Asset"
    | "Speaker Profile"
    | "PDF Profile";
  tags: string[];
  featured?: boolean;
};

export type PressStat = {
  value: string;
  label: string;
  icon: "news" | "tv" | "award" | "global";
};

export type AuthorityLogo = {
  name: string;
  type: "Media" | "Television" | "Newspaper" | "Platform" | "Institution";
  image?: string;
};

export type InternationalCoverage = {
  id: string;
  country: PressRegion;
  publisher: string;
  title: string;
  summary: string;
  image: string;
  alt: string;
  tags: string[];
  url?: string;
};

export type TimelineItem = {
  year: string;
  title: string;
  outlet: string;
  summary: string;
  image: string;
  alt: string;
};

export const pressPath = "/assets/press/";
export const latestPath = `${pressPath}latest-speaks/`;

export const pressSeo = {
  title:
    "Press News | Arijit Bhattacharyya | Media Coverage, Interviews, TV & Global Recognition",
  description:
    "Press, television, interviews, media stories and global recognition featuring Arijit Bhattacharyya across entrepreneurship, AI, VR, blockchain, startup mentoring, gaming, innovation, media, entertainment technology and global speaking.",
  keywords:
    "Arijit Bhattacharyya press, Arijit Bhattacharyya news, Arijit Bhattacharya, BrilliantRead Arijit Bhattacharyya, TEDx speaker, angel investor, serial entrepreneur, Virtualinfocom, Economic Times, Times of India, Hindustan Times, Business Standard, TV9 Bengali, CNBC, Josh Talks, Nepal TV, China Film Festival, startup mentor, AI speaker, VR speaker, blockchain speaker, media coverage, press coverage",
};

export const heroStats: PressStat[] = [
  { value: "100+", label: "Media Mentions & Features", icon: "news" },
  { value: "25+", label: "TV, Video & Interview Appearances", icon: "tv" },
  { value: "20+", label: "Countries Connected Through Coverage", icon: "global" },
  { value: "1998", label: "Founder Journey Since", icon: "award" },
];

export const featuredStories: PressStory[] = [
  {
    id: "brilliantread-interview",
    title:
      "Interview with Arijit Bhattacharyya, Angel Investor, Serial Entrepreneur, Mentor & TEDx Speaker",
    outlet: "BrilliantRead",
    publisher: "BrilliantRead",
    category: "Interview",
    type: "Interview",
    region: "India",
    country: "India",
    year: "2020s",
    eyebrow: "Founder Interview",
    summary:
      "A long-form interview positioning Arijit Bhattacharyya as an angel investor, serial entrepreneur, mentor and TEDx speaker, useful for current credibility beyond legacy press clippings.",
    image: `${latestPath}Arijit-Bhattacharyya.jpg`,
    alt:
      "Arijit Bhattacharyya featured interview as angel investor serial entrepreneur mentor and TEDx speaker",
    url:
      "https://www.brilliantread.com/interview-with-arijit-bhattacharyya-angel-investor-serial-entrepreneur-mentor-tedx-speaker/",
    sourceType: "External Profile",
    tags: ["Interview", "Angel Investor", "TEDx", "Entrepreneurship"],
    featured: true,
  },
  {
    id: "digitalconfex-speaker-profile",
    title: "Serial Entrepreneur, Angel Investor, Public Speaker and AI Evangelist",
    outlet: "DigitalConfex",
    publisher: "DigitalConfex",
    category: "Speaker Profile",
    type: "Interview",
    region: "Global",
    country: "Global",
    year: "2023",
    eyebrow: "Global Speaker Profile",
    summary:
      "DigitalConfex profiles Arijit as a serial entrepreneur since 1998, angel investor, public speaker, government advisor, game programmer, VR specialist, AI evangelist and blockchain specialist.",
    image: `${latestPath}Arij_Bhattacharyya-talk.jpg`,
    alt:
      "Arijit Bhattacharyya DigitalConfex speaker profile for AI entrepreneurship VR blockchain and startup mentoring",
    url: "https://digitalconfex.com/speaker/arijit-bhattacharyya/",
    sourceType: "Speaker Profile",
    tags: ["AI", "VR", "Blockchain", "Speaker"],
    featured: true,
  },
  {
    id: "diplomatic-club-profile",
    title: "Entrepreneur Since 1998, TEDx and International Speaker",
    outlet: "The Diplomatic Club",
    publisher: "The Diplomatic Club",
    category: "Profile",
    type: "International",
    region: "Global",
    country: "Global",
    year: "2024",
    eyebrow: "Business Diplomacy",
    summary:
      "The Diplomatic Club presents Arijit Bhattacharyya as an entrepreneur since 1998, TEDx and international speaker, angel investor, business matchmaking expert and government advisory voice.",
    image: `${pressPath}2021/diplomatic-world.jpg`,
    alt:
      "Arijit Bhattacharyya profile in The Diplomatic Club entrepreneur TEDx international speaker",
    url: "https://www.thediplomaticclub.org/arijit-bhattacharyya/",
    sourceType: "External Profile",
    tags: ["Diplomacy", "International", "TEDx", "Advisory"],
    featured: true,
  },
  {
    id: "official-profile-pdf",
    title: "Official Profile: Technology, Startups, AI, VR and Global Innovation",
    outlet: "Official Profile PDF",
    publisher: "Official Profile PDF",
    category: "Profile",
    type: "Interview",
    region: "Global",
    country: "Global",
    year: "2023",
    eyebrow: "Verified Profile",
    summary:
      "The profile PDF consolidates key credibility points including startup mentoring, global speaking, Startup India Award jury work, Asian Development Bank consulting, blockchain thought leadership and university engagement.",
    image: `${pressPath}2018/Arijit_Bhattacharyya.jpg`,
    alt:
      "Official profile of Arijit Bhattacharyya covering technology startup mentoring AI VR and global innovation",
    url:
      "https://digitalconfex.com/wp-content/uploads/2023/06/Arijit-Bhattacharyya_1998-brief.pdf",
    sourceType: "PDF Profile",
    tags: ["Profile", "Startup India", "ADB", "Global Speaker"],
    featured: true,
  },
];

export const authorityLogos: AuthorityLogo[] = [
  { name: "Economic Times", type: "Newspaper", image: `${pressPath}2018/economic-times.jpg` },
  { name: "Times of India", type: "Newspaper", image: `${pressPath}2024/timesofindia-s.jpg` },
  { name: "The Hindu", type: "Newspaper", image: `${pressPath}2019/the-hindu.png` },
  { name: "Anandabazar Patrika", type: "Newspaper", image: `${pressPath}2020/anandabazar-abp.jpg` },
  { name: "Hindustan Times", type: "Newspaper", image: `${pressPath}hindustantimes.png` },
  { name: "Business Standard", type: "Newspaper", image: `${pressPath}business standard.png` },
  { name: "TV9 Bengali", type: "Television", image: `${latestPath}TV9.jpg` },
  { name: "CNBC", type: "Television", image: `${latestPath}cnbc.jpg` },
  { name: "DD Bangla", type: "Television", image: `${pressPath}2019/DD-Bangla.jpg` },
  { name: "Josh Talks", type: "Platform", image: `${pressPath}2018/Josh-Talk_Bengali.jpg` },
  { name: "Nepal TV", type: "Television", image: `${latestPath}nepal.jpg` },
  { name: "Kantipur Media", type: "Media", image: `${pressPath}2018/kantipur_media.jpg` },
  { name: "DigitalConfex", type: "Platform" },
  { name: "BrilliantRead", type: "Media" },
];

export const mediaLogos = authorityLogos;

export const mediaAuthorityGrid: PressStory[] = [
  {
    id: "economic-times-press",
    title: "Press News About Arijit in Economic Times",
    outlet: "Economic Times",
    publisher: "Economic Times",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "National Business Media",
    summary:
      "Legacy press coverage connecting Arijit Bhattacharyya's work with entrepreneurship, innovation, startup building and technology leadership.",
    image: `${pressPath}2018/economic-times.jpg`,
    alt: "Economic Times press coverage about Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["Economic Times", "Business", "Startup"],
  },
  {
    id: "times-of-india-2024",
    title: "Times of India Coverage",
    outlet: "Times of India",
    publisher: "Times of India",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "2024",
    eyebrow: "National Newspaper",
    summary:
      "Times of India coverage included in the legacy press archive, supporting Arijit's public positioning across innovation and entrepreneurship.",
    image: `${pressPath}2024/timesofindia-s.jpg`,
    alt: "Times of India press coverage of Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["Times of India", "Press", "Innovation"],
  },
  {
    id: "anandabazar-2024",
    title: "Anandabazar Coverage",
    outlet: "Anandabazar Patrika",
    publisher: "Anandabazar Patrika",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "2024",
    eyebrow: "Bengali Press",
    summary:
      "Bengali press coverage from Anandabazar strengthens regional credibility around Arijit's work in technology, gaming, startups and public speaking.",
    image: `${pressPath}2020/anandabazar-abp.jpg`,
    alt: "Anandabazar press coverage of Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["Anandabazar", "Bengal", "Press"],
  },
  {
    id: "the-hindu-coverage",
    title: "The Hindu Coverage",
    outlet: "The Hindu",
    publisher: "The Hindu",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "National Publication",
    summary:
      "The Hindu coverage forms part of the old press archive and adds national publication credibility to the press page.",
    image: `${pressPath}2019/the-hindu.png`,
    alt: "The Hindu article coverage connected to Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["The Hindu", "Publication", "Technology"],
  },
  {
    id: "aajkal-coverage",
    title: "Aajkal Coverage",
    outlet: "Aajkal",
    publisher: "Aajkal",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Regional Press",
    summary:
      "Regional newspaper coverage from Aajkal documenting Arijit's work in innovation, entrepreneurship and media technology.",
    image: `${pressPath}2020/aajkal.jpg`,
    alt: "Aajkal newspaper coverage of Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Aajkal", "Bengali Press", "Legacy"],
  },
  {
    id: "diplomatic-world",
    title: "Diplomatic World Feature",
    outlet: "Diplomatic World",
    publisher: "Diplomatic World",
    category: "Magazine",
    type: "Magazine",
    region: "Global",
    country: "Global",
    year: "Legacy",
    eyebrow: "Magazine Feature",
    summary:
      "Diplomatic World coverage connects Arijit's work with international networks, public diplomacy, business collaboration and innovation.",
    image: `${pressPath}2021/diplomatic-world-one.jpg`,
    alt: "Diplomatic World magazine feature about Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Diplomatic World", "Global", "Magazine"],
  },
];

export const additionalMediaAuthority: PressStory[] = [
  {
    id: "hindustan-times-coverage",
    title: "Hindustan Times Coverage",
    outlet: "Hindustan Times",
    publisher: "Hindustan Times",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "National Newspaper",
    summary:
      "National press coverage strengthening Arijit Bhattacharyya's public profile across entrepreneurship, technology, innovation and startup ecosystem work.",
    image: `${pressPath}hindustantimes.png`,
    alt: "Hindustan Times press coverage featuring Arijit Bhattacharyya entrepreneur and technology innovator",
    sourceType: "Press Asset",
    tags: ["Hindustan Times", "National Media", "Entrepreneurship"],
  },
  {
    id: "hindustan-times-archive",
    title: "Hindustan Times Archive Feature",
    outlet: "Hindustan Times",
    publisher: "Hindustan Times",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "National Press Archive",
    summary:
      "Additional Hindustan Times archive item preserving legacy newspaper visibility around Arijit's work in entrepreneurship, technology and innovation.",
    image: `${pressPath}hindusthantimes.jpg`,
    alt: "Hindustan Times archive coverage of Arijit Bhattacharyya and his technology entrepreneurship work",
    sourceType: "Press Asset",
    tags: ["Hindustan Times", "Press Archive", "Innovation"],
  },
  {
    id: "business-standard-coverage",
    title: "Business Standard Coverage",
    outlet: "Business Standard",
    publisher: "Business Standard",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Newspaper",
    summary:
      "Business media archive coverage connected to Arijit's role as an entrepreneur, mentor, investor, technologist and business ecosystem builder.",
    image: `${pressPath}business standard.png`,
    alt: "Business Standard media coverage of Arijit Bhattacharyya business strategist and entrepreneur",
    sourceType: "Press Asset",
    tags: ["Business Standard", "Business Media", "Startup"],
  },
  {
    id: "business-world-profile",
    title: "Business World Feature",
    outlet: "Business World",
    publisher: "Business World",
    category: "Magazine",
    type: "Magazine",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Magazine",
    summary:
      "Business World archive asset connecting Arijit Bhattacharyya with business leadership, entrepreneurship and technology-led growth conversations.",
    image: `${pressPath}arijit-bhattacharyya_business-world.jpg`,
    alt: "Business World feature with Arijit Bhattacharyya entrepreneur and innovation leader",
    sourceType: "Press Asset",
    tags: ["Business World", "Magazine", "Innovation"],
  },
  {
    id: "economics-profile",
    title: "Economic Coverage and Founder Profile",
    outlet: "Economics / Business Media",
    publisher: "Business Media",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Recognition",
    summary:
      "Business and economic coverage documenting Arijit's founder journey, venture building, startup mentoring and technology ecosystem leadership.",
    image: `${pressPath}Arijit-Bhattacharyya-ECONOMICS.jpg`,
    alt: "Economic and business media coverage featuring Arijit Bhattacharyya founder entrepreneur and startup mentor",
    sourceType: "Press Asset",
    tags: ["Business", "Economics", "Founder"],
  },
  {
    id: "abp-bangla-coverage",
    title: "ABP Bangla Coverage",
    outlet: "ABP Bangla",
    publisher: "ABP Bangla",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Regional Media",
    summary:
      "Regional Bengali media coverage supporting Arijit's Bengal-origin story across technology, entrepreneurship, gaming, mentoring and media work.",
    image: `${pressPath}ABP bangla.png`,
    alt: "ABP Bangla coverage of Arijit Bhattacharyya technology entrepreneur from Bengal",
    sourceType: "Press Asset",
    tags: ["ABP Bangla", "Bengal", "Regional Press"],
  },
  {
    id: "abp-arijit-profile",
    title: "ABP Media Feature",
    outlet: "ABP",
    publisher: "ABP",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Regional Press Archive",
    summary:
      "ABP archive feature connected to Arijit's visibility in regional press, entrepreneurship, technology and creative media ecosystems.",
    image: `${pressPath}ABP_Arijit.jpg`,
    alt: "ABP media feature with Arijit Bhattacharyya entrepreneur and technology speaker",
    sourceType: "Press Asset",
    tags: ["ABP", "Regional Media", "Press"],
  },
  {
    id: "tv9-archive-coverage",
    title: "TV9 Press Archive",
    outlet: "TV9",
    publisher: "TV9",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Television Media",
    summary:
      "Additional TV9 archive asset strengthening television and regional media proof around Arijit's work in gaming, VR, startups and technology.",
    image: `${pressPath}TV9-2.png`,
    alt: "TV9 archive coverage featuring Arijit Bhattacharyya gaming VR and technology work",
    sourceType: "Press Asset",
    tags: ["TV9", "Television", "VR"],
  },
  {
    id: "arijit-news-archive",
    title: "Arijit Bhattacharyya News Archive",
    outlet: "Press Archive",
    publisher: "Press Archive",
    category: "Newspaper",
    type: "Newspaper",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Legacy News",
    summary:
      "Legacy news coverage connected to Arijit Bhattacharyya's public profile across entrepreneurship, media, innovation and technology-led platforms.",
    image: `${pressPath}arijit-news.jpg`,
    alt: "Legacy press news archive about Arijit Bhattacharyya entrepreneur and technology speaker",
    sourceType: "Press Asset",
    tags: ["News", "Legacy", "Press"],
  },
];

export const mediaAuthority: PressStory[] = [
  ...mediaAuthorityGrid,
  ...additionalMediaAuthority,
];

export const tvAndVideoCoverage: PressStory[] = [
  {
    id: "tv9-game-development-vr",
    title: "TV9 Bengali Game Development and VR Coverage",
    outlet: "TV9 Bengali",
    publisher: "TV9 Bengali",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Television Feature",
    summary:
      "TV9 Bengali coverage on game development, VR and Arijit's role in building technology-led entertainment from Bengal.",
    image: `${latestPath}TV9.jpg`,
    alt: "TV9 Bengali coverage on Arijit Bhattacharyya game development and VR",
    sourceType: "Legacy Website",
    tags: ["TV9", "VR", "Game Development"],
  },
  {
    id: "cnbc-talk",
    title: "Talk in CNBC",
    outlet: "CNBC",
    publisher: "CNBC",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Television",
    summary:
      "CNBC appearance from the legacy archive, adding business media validation around entrepreneurship, markets and technology.",
    image: `${latestPath}cnbc.jpg`,
    alt: "CNBC television talk featuring Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["CNBC", "Business Media", "TV"],
  },
  {
    id: "dd-bangla-vr-growth",
    title: "Speaking on Growth of VR in Television",
    outlet: "DD Bangla",
    publisher: "DD Bangla",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Public Television",
    summary:
      "Television coverage discussing the growth of virtual reality and Arijit's contribution to immersive technology education and development.",
    image: `${pressPath}2019/DD-Bangla.jpg`,
    alt: "DD Bangla television coverage on VR growth featuring Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["DD Bangla", "VR", "Television"],
  },
  {
    id: "josh-talk-bengali",
    title: "Josh Talk Bengali",
    outlet: "Josh Talks",
    publisher: "Josh Talks",
    category: "Interview",
    type: "Interview",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Founder Storytelling",
    summary:
      "Josh Talks appearance presenting Arijit's entrepreneurial journey, technology work and founder lessons to a broader Bengali-speaking audience.",
    image: `${pressPath}2018/Josh-Talk_Bengali.jpg`,
    alt: "Josh Talk Bengali featuring Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["Josh Talks", "Storytelling", "Bengali"],
  },
  {
    id: "tedx-talk",
    title: "TEDx Talk",
    outlet: "TEDx",
    publisher: "TEDx",
    category: "Interview",
    type: "Interview",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "TEDx Speaker",
    summary:
      "TEDx speaker credibility connected to Arijit's public work in technology, entrepreneurship, innovation and storytelling.",
    image: `${pressPath}2019/tedx.jpg`,
    alt: "Arijit Bhattacharyya TEDx speaker coverage",
    sourceType: "Press Asset",
    tags: ["TEDx", "Speaker", "Ideas"],
  },
  {
    id: "nepal-tv",
    title: "Nepal TV / Good Morning Nepal",
    outlet: "Nepal TV",
    publisher: "Nepal TV",
    category: "Television",
    type: "TV",
    region: "Nepal",
    country: "Nepal",
    year: "Legacy",
    eyebrow: "International Television",
    summary:
      "Nepal TV and Good Morning Nepal coverage documenting cross-border startup mentoring, entrepreneurship and regional innovation conversations.",
    image: `${latestPath}nepal.jpg`,
    alt: "Nepal TV and Good Morning Nepal coverage featuring Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["Nepal TV", "International", "Startup"],
  },
];

export const additionalTvCoverage: PressStory[] = [
  {
    id: "cnbc-arijit-interview",
    title: "CNBC Interview and Business Television Coverage",
    outlet: "CNBC",
    publisher: "CNBC",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Television",
    summary:
      "CNBC archive coverage strengthening Arijit's media credibility across business, technology, entrepreneurship and innovation conversations.",
    image: `${pressPath}cnbc_arijit.jpg`,
    alt: "CNBC business television coverage featuring Arijit Bhattacharyya entrepreneur and technology expert",
    sourceType: "Press Asset",
    tags: ["CNBC", "Business TV", "Entrepreneurship"],
  },
  {
    id: "nepal-tv-arijit",
    title: "Nepal TV Coverage Featuring Arijit Bhattacharyya",
    outlet: "Nepal TV",
    publisher: "Nepal TV",
    category: "Television",
    type: "TV",
    region: "Nepal",
    country: "Nepal",
    year: "Legacy",
    eyebrow: "International Television",
    summary:
      "Nepal television coverage showing Arijit's cross-border work across startups, entrepreneurship, mentoring and regional innovation ecosystems.",
    image: `${pressPath}Nepal_TV_Arijit-Bhattacharyya.png`,
    alt: "Nepal TV coverage featuring Arijit Bhattacharyya international startup mentor and speaker",
    sourceType: "Press Asset",
    tags: ["Nepal TV", "International", "Startup"],
  },
  {
    id: "mtv-india-coverage",
    title: "MTV India Media Coverage",
    outlet: "MTV India",
    publisher: "MTV India",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Youth Media",
    summary:
      "MTV India archive asset connecting Arijit's media presence with youth culture, entertainment, creative technology and public visibility.",
    image: `${pressPath}mtv_India.jpg`,
    alt: "MTV India media coverage connected to Arijit Bhattacharyya creative technology and entertainment work",
    sourceType: "Press Asset",
    tags: ["MTV India", "Media", "Entertainment"],
  },
  {
    id: "mtv-coverage",
    title: "MTV Media Archive",
    outlet: "MTV",
    publisher: "MTV",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Television Archive",
    summary:
      "MTV archive asset connected to creative culture, youth media, entertainment technology and Arijit's broader public-facing media work.",
    image: `${pressPath}mtv.jpg`,
    alt: "MTV media archive coverage connected to Arijit Bhattacharyya creative and entertainment work",
    sourceType: "Press Asset",
    tags: ["MTV", "Creative Media", "Television"],
  },
  {
    id: "kantipur-tv-coverage",
    title: "Kantipur TV Coverage",
    outlet: "Kantipur TV",
    publisher: "Kantipur TV",
    category: "Television",
    type: "TV",
    region: "Nepal",
    country: "Nepal",
    year: "2018",
    eyebrow: "International Television",
    summary:
      "Kantipur TV coverage from Nepal documenting Arijit's regional startup, mentoring and entrepreneurship engagement.",
    image: `${pressPath}2018/kantipur_TV.jpg`,
    alt: "Kantipur TV Nepal coverage featuring Arijit Bhattacharyya startup mentor and speaker",
    sourceType: "Press Asset",
    tags: ["Kantipur TV", "Nepal", "Television"],
  },
  {
    id: "dd-bangla-latest",
    title: "DD Bangla Television Appearance",
    outlet: "DD Bangla",
    publisher: "DD Bangla",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Public Television",
    summary:
      "DD Bangla television archive asset connected to Arijit's work in VR, technology education, innovation and public communication.",
    image: `${latestPath}DD_bangla.jpg`,
    alt: "DD Bangla television appearance with Arijit Bhattacharyya on technology and VR",
    sourceType: "Press Asset",
    tags: ["DD Bangla", "VR", "Television"],
  },
  {
    id: "star-ananda-archive",
    title: "Star Ananda Media Coverage",
    outlet: "Star Ananda",
    publisher: "Star Ananda",
    category: "Television",
    type: "TV",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Regional Television",
    summary:
      "Regional television archive asset connected to Arijit's public profile across technology, entrepreneurship, innovation and media.",
    image: `${pressPath}star.jpg`,
    alt: "Star Ananda television coverage featuring Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Star Ananda", "Television", "Regional"],
  },
];

export const completeTvAndVideoCoverage: PressStory[] = [
  ...tvAndVideoCoverage,
  ...additionalTvCoverage,
];

export const internationalCoverage: InternationalCoverage[] = [
  {
    id: "china-film-festival",
    country: "China",
    publisher: "China Film Festival",
    title: "China Film Festival and Xian Film Festival",
    summary:
      "Coverage and event presence connected to China film festival participation, Xian speaking engagement, entertainment technology and cross-border creative industries.",
    image: `${pressPath}2020/China-blockchain.jpg`,
    alt: "Arijit Bhattacharyya China film festival and Xian coverage",
    tags: ["China", "Film Festival", "Entertainment Technology"],
  },
  {
    id: "nepal-startup-coverage",
    country: "Nepal",
    publisher: "Kantipur Media",
    title: "Nepal Startup and Media Coverage",
    summary:
      "Coverage across Nepal startup events, Kantipur Media, Nepal news and television appearances highlighting regional entrepreneurship work.",
    image: `${pressPath}2018/kantipur_media.jpg`,
    alt: "Kantipur Media and Nepal startup coverage of Arijit Bhattacharyya",
    tags: ["Nepal", "Kantipur", "Startup"],
  },
  {
    id: "finland-india-coverage",
    country: "Finland",
    publisher: "Invest Finland",
    title: "Invest Finland and India",
    summary:
      "Legacy archive coverage connecting international investment, India-Finland collaboration and business ecosystem building.",
    image: `${pressPath}2018/Finland_India.jpg`,
    alt: "Invest Finland and India coverage featuring Arijit Bhattacharyya",
    tags: ["Finland", "India", "Investment"],
  },
  {
    id: "bhutan-coverage",
    country: "Bhutan",
    publisher: "Regional Entrepreneurship",
    title: "Bhutan and Regional Entrepreneurship",
    summary:
      "Regional business and innovation links connected to Bhutan and cross-border startup ecosystem conversations.",
    image: `${latestPath}bhutan.png`,
    alt: "Bhutan entrepreneurship and regional innovation coverage",
    tags: ["Bhutan", "Regional", "Entrepreneurship"],
  },
  {
    id: "thailand-techsauce",
    country: "Thailand",
    publisher: "Techsauce",
    title: "Techsauce / Startup Thailand",
    summary:
      "International startup ecosystem connection through Techsauce and Thailand-linked entrepreneurship platforms.",
    image: `${pressPath}2018/tech-sauce.jpg`,
    alt: "Techsauce and Thailand startup ecosystem coverage",
    tags: ["Thailand", "Techsauce", "Startup"],
  },
  {
    id: "singapore-ecosystem",
    country: "Singapore",
    publisher: "Asian Business Networks",
    title: "Singapore Business and Technology Ecosystem",
    summary:
      "International technology and startup ecosystem engagement connected to Asian business networks and innovation platforms.",
    image: `${pressPath}Singapore_Arijit.jpg`,
    alt: "International business and technology ecosystem coverage of Arijit Bhattacharyya",
    tags: ["Singapore", "Business", "Technology"],
  },
];

export const additionalInternationalCoverage: InternationalCoverage[] = [
  {
    id: "china-film-festival-asset",
    country: "China",
    publisher: "China Film Festival",
    title: "China Film Festival Coverage",
    summary:
      "China Film Festival archive asset supporting Arijit's international entertainment technology, film, games and creative industry presence.",
    image: `${pressPath}China_film_fest.jpg`,
    alt: "China Film Festival coverage featuring Arijit Bhattacharyya entertainment technology and international media presence",
    tags: ["China", "Film Festival", "Entertainment"],
  },
  {
    id: "japan-coverage",
    country: "Global",
    publisher: "Japan Business / Technology Archive",
    title: "Japan Technology and Business Connection",
    summary:
      "Japan-linked archive asset supporting Arijit's international technology, startup and business ecosystem footprint.",
    image: `${pressPath}japan.jpg`,
    alt: "Japan business and technology archive coverage connected to Arijit Bhattacharyya",
    tags: ["Japan", "International", "Technology"],
  },
  {
    id: "taiwan-coverage",
    country: "Global",
    publisher: "Taiwan Archive",
    title: "Taiwan Technology and Startup Connection",
    summary:
      "Taiwan-linked archive asset extending the international coverage layer across Asian innovation and technology ecosystems.",
    image: `${pressPath}taiwan.jpg`,
    alt: "Taiwan technology and startup ecosystem coverage connected to Arijit Bhattacharyya",
    tags: ["Taiwan", "Asia", "Technology"],
  },
  {
    id: "south-korea-game",
    country: "Global",
    publisher: "South Korea Game Archive",
    title: "South Korea Game and Technology Coverage",
    summary:
      "South Korea game-industry archive asset connected to Arijit's global gaming, VR and entertainment technology footprint.",
    image: `${pressPath}south_Korea_game.jpg`,
    alt: "South Korea game technology coverage connected to Arijit Bhattacharyya",
    tags: ["South Korea", "Gaming", "Technology"],
  },
  {
    id: "arijit-nepal-archive",
    country: "Nepal",
    publisher: "Nepal Media Archive",
    title: "Nepal Media and Startup Coverage",
    summary:
      "Nepal archive assets documenting Arijit's cross-border startup mentoring, speaking and entrepreneurship ecosystem work.",
    image: `${pressPath}Arijit_Bhattacharyya_Nepal.png`,
    alt: "Nepal media coverage featuring Arijit Bhattacharyya startup mentor and international speaker",
    tags: ["Nepal", "Startup", "Speaker"],
  },
  {
    id: "nepal-news-archive",
    country: "Nepal",
    publisher: "Nepal News",
    title: "Nepal News Coverage",
    summary:
      "Nepal news archive item preserving regional media visibility around Arijit's entrepreneurship and mentoring work.",
    image: `${pressPath}2018/nepal_news.jpg`,
    alt: "Nepal News coverage of Arijit Bhattacharyya entrepreneurship and mentoring work",
    tags: ["Nepal", "News", "Entrepreneurship"],
  },
  {
    id: "world-leadership-conference",
    country: "Global",
    publisher: "World Leadership Conference",
    title: "World Leadership Conference Coverage",
    summary:
      "World Leadership Conference archive assets documenting global leadership, speaking and entrepreneurship conversations connected to Arijit.",
    image: `${pressPath}2020/World-Leadership-Conference-Arijit.jpg`,
    alt: "World Leadership Conference coverage featuring Arijit Bhattacharyya global speaker and entrepreneur",
    tags: ["Global", "Leadership", "Speaking"],
  },
];

export const completeInternationalCoverage: InternationalCoverage[] = [
  ...internationalCoverage,
  ...additionalInternationalCoverage,
];

export const legacyPressArchive: PressStory[] = [
  {
    id: "icc-startuppad",
    title: "ICC Startuppad",
    outlet: "ICC",
    publisher: "ICC",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "2018",
    eyebrow: "Startup Platform",
    summary:
      "ICC Startuppad coverage from the legacy archive, connecting Arijit with startup mentoring, pitching and business ecosystem development.",
    image: `${pressPath}2018/ICC_Startupad_American_Center-Arijit.jpg`,
    alt: "ICC Startuppad American Center coverage with Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["ICC", "Startup", "Mentoring"],
  },
  {
    id: "nen",
    title: "NEN",
    outlet: "National Entrepreneurship Network",
    publisher: "National Entrepreneurship Network",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Entrepreneurship Network",
    summary:
      "NEN archive item connected to entrepreneurship mentoring, student founders and startup ecosystem development.",
    image: `${pressPath}nen.jpg`,
    alt: "NEN entrepreneurship coverage featuring Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["NEN", "Entrepreneurship", "Mentoring"],
  },
  {
    id: "tiecon-punjab",
    title: "TiECon Punjab",
    outlet: "TiE",
    publisher: "TiE",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Founder Ecosystem",
    summary:
      "TiECon Punjab coverage from the archive, documenting founder ecosystem engagement and startup conversations.",
    image: `${pressPath}2018/tiecon_punjab.jpg`,
    alt: "TiECon Punjab coverage featuring Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["TiE", "Punjab", "Startup"],
  },
  {
    id: "iamai",
    title: "IAMAI",
    outlet: "IAMAI",
    publisher: "IAMAI",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Digital Industry",
    summary:
      "IAMAI archive item connected to digital business, internet economy and technology ecosystem work.",
    image: `${pressPath}2018/IAMAI.jpg`,
    alt: "IAMAI event coverage with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["IAMAI", "Digital", "Industry"],
  },
  {
    id: "ieee-money-on-table",
    title: "IEEE Money on Table",
    outlet: "IEEE",
    publisher: "IEEE",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Technology & Investment",
    summary:
      "IEEE archive coverage linking technology, investment conversations and entrepreneurship education.",
    image: `${pressPath}2018/IEEE-money-on-table.jpg`,
    alt: "IEEE Money on Table event coverage with Arijit Bhattacharyya",
    sourceType: "Legacy Website",
    tags: ["IEEE", "Investment", "Technology"],
  },
  {
    id: "gato-vr-ar-gaming",
    title: "GATO 1.0 — VR, AR and Gaming",
    outlet: "GATO",
    publisher: "GATO",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Gaming & Immersive Tech",
    summary:
      "GATO archive item connected to VR, AR, gaming and emerging entertainment technology.",
    image: `${pressPath}2019/GATO-vr-ar-gaming.png`,
    alt: "GATO VR AR gaming coverage featuring Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["VR", "AR", "Gaming"],
  },
  {
    id: "axis-bank-speaking",
    title: "Axis Bank Speaking Engagement",
    outlet: "Axis Bank",
    publisher: "Axis Bank",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Corporate Speaking",
    summary:
      "Corporate speaking engagement connected to business, finance, entrepreneurship and innovation discussions.",
    image: `${pressPath}2020/axis-bank-spk.jpg`,
    alt: "Axis Bank speaking engagement with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Corporate", "Finance", "Speaking"],
  },
  {
    id: "calcutta-chamber-commerce",
    title: "Calcutta Chamber of Commerce",
    outlet: "Calcutta Chamber of Commerce",
    publisher: "Calcutta Chamber of Commerce",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Chamber",
    summary:
      "Business chamber engagement connected to entrepreneurship, industry development and Bengal's business ecosystem.",
    image: `${pressPath}2020/calcutta-chamber-of-commerce.jpg`,
    alt: "Calcutta Chamber of Commerce coverage with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Chamber", "Business", "Bengal"],
  },
  {
    id: "iim-bodhgaya",
    title: "IIM Bodh Gaya",
    outlet: "IIM Bodh Gaya",
    publisher: "IIM Bodh Gaya",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Institutional Talk",
    summary:
      "Institutional engagement connected to management education, entrepreneurship and innovation.",
    image: `${pressPath}2020/IIM_Bodhgaya.jpg`,
    alt: "IIM Bodh Gaya event coverage with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["IIM", "Education", "Entrepreneurship"],
  },
  {
    id: "nit-silchar",
    title: "NIT Silchar Startup Session",
    outlet: "NIT Silchar",
    publisher: "NIT Silchar",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "University Entrepreneurship",
    summary:
      "University startup session connected to mentoring young founders and future technology learners.",
    image: `${pressPath}2019/NIT-Silchar-startup.jpg`,
    alt: "NIT Silchar startup event with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["NIT", "Startup", "Students"],
  },
  {
    id: "short-film-festival-kolkata",
    title: "Short Film Festival Kolkata",
    outlet: "Kolkata Short Film Festival",
    publisher: "Kolkata Short Film Festival",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Creative Industry",
    summary:
      "Creative and film ecosystem coverage connected to storytelling, media, animation and entertainment technology.",
    image: `${pressPath}2019/short-film-festival-kolkata.jpg`,
    alt: "Short Film Festival Kolkata coverage with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Film", "Creative", "Kolkata"],
  },
  {
    id: "mrs-india",
    title: "Mrs India",
    outlet: "Mrs India",
    publisher: "Mrs India",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Creative & Cultural Platform",
    summary:
      "Legacy event item connected to media, culture and public-facing creative platforms.",
    image: `${pressPath}2018/Mrs_India.jpg`,
    alt: "Mrs India event coverage with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Culture", "Event", "Media"],
  },
];

export const additionalLegacyPressArchive: PressStory[] = [
  {
    id: "assocham-archive",
    title: "ASSOCHAM Business Platform",
    outlet: "ASSOCHAM",
    publisher: "ASSOCHAM",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Chamber",
    summary:
      "ASSOCHAM archive asset connected to entrepreneurship, business development, industry platforms and strategic ecosystem conversations.",
    image: `${pressPath}assocham.jpg`,
    alt: "ASSOCHAM business platform coverage with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["ASSOCHAM", "Business", "Industry"],
  },
  {
    id: "bcci-business-chamber",
    title: "Bengal Chamber and Commerce Ecosystem",
    outlet: "BCC&I",
    publisher: "BCC&I",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Chamber",
    summary:
      "Business chamber archive asset supporting Arijit's Bengal business ecosystem, entrepreneurship and industry network credibility.",
    image: `${pressPath}bcc&i.jpg`,
    alt: "BCC&I business chamber coverage with Arijit Bhattacharyya entrepreneur and mentor",
    sourceType: "Press Asset",
    tags: ["BCC&I", "Chamber", "Bengal"],
  },
  {
    id: "indian-chamber-commerce",
    title: "Indian Chamber of Commerce",
    outlet: "Indian Chamber of Commerce",
    publisher: "Indian Chamber of Commerce",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Business Chamber",
    summary:
      "Indian Chamber of Commerce archive coverage connected to business leadership, startup platforms and entrepreneurship mentoring.",
    image: `${pressPath}Indian_Chamber_of_Commerce.jpg`,
    alt: "Indian Chamber of Commerce event with Arijit Bhattacharyya business mentor and entrepreneur",
    sourceType: "Press Asset",
    tags: ["ICC", "Business", "Startup"],
  },
  {
    id: "icc-startup-funding",
    title: "ICC Startup Funding Platform",
    outlet: "ICC",
    publisher: "ICC",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Startup Funding",
    summary:
      "ICC Startup Funding archive asset connected to founder mentoring, pitch readiness, investor conversations and startup ecosystem building.",
    image: `${pressPath}ICC_Startup_Funding.jpg`,
    alt: "ICC Startup Funding event with Arijit Bhattacharyya startup mentor and investor advisor",
    sourceType: "Press Asset",
    tags: ["ICC", "Funding", "Startup"],
  },
  {
    id: "google-business-group",
    title: "Google Business Group",
    outlet: "Google Business Group",
    publisher: "Google Business Group",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Startup Ecosystem",
    summary:
      "Google Business Group archive asset supporting Arijit's mentoring and ecosystem-building work across founders, technology and digital business.",
    image: `${pressPath}Google_Business_group.jpg`,
    alt: "Google Business Group event with Arijit Bhattacharyya startup mentor and technology speaker",
    sourceType: "Press Asset",
    tags: ["Google Business Group", "Startup", "Digital"],
  },
  {
    id: "iit-kharagpur",
    title: "IIT Kharagpur Engagement",
    outlet: "IIT Kharagpur",
    publisher: "IIT Kharagpur",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Institutional Technology Platform",
    summary:
      "IIT Kharagpur archive asset strengthening institutional credibility across technology, entrepreneurship, innovation and student-founder ecosystems.",
    image: `${pressPath}IIT-Kharagpur.jpg`,
    alt: "IIT Kharagpur event with Arijit Bhattacharyya technology speaker and mentor",
    sourceType: "Press Asset",
    tags: ["IIT Kharagpur", "Technology", "Students"],
  },
  {
    id: "iit-hyderabad",
    title: "IIT Hyderabad Engagement",
    outlet: "IIT Hyderabad",
    publisher: "IIT Hyderabad",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Technology Institution",
    summary:
      "IIT Hyderabad archive asset connected to technology, innovation, student founders and deeptech ecosystem conversations.",
    image: `${pressPath}IIT-Hydrabad.jpg`,
    alt: "IIT Hyderabad event with Arijit Bhattacharyya deeptech speaker and startup mentor",
    sourceType: "Press Asset",
    tags: ["IIT Hyderabad", "DeepTech", "Innovation"],
  },
  {
    id: "hult-kolkata",
    title: "HULT Kolkata",
    outlet: "HULT",
    publisher: "HULT",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "2019",
    eyebrow: "Student Entrepreneurship",
    summary:
      "HULT Kolkata archive item connected to student entrepreneurship, global business thinking and startup ecosystem mentoring.",
    image: `${pressPath}2019/HULT-Kolkata.jpg`,
    alt: "HULT Kolkata entrepreneurship event with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["HULT", "Students", "Entrepreneurship"],
  },
  {
    id: "nit-startup",
    title: "NIT Startup Platform",
    outlet: "NIT",
    publisher: "NIT",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "2019",
    eyebrow: "University Startup Ecosystem",
    summary:
      "NIT startup archive asset connected to mentoring student founders, startup education and future technology entrepreneurship.",
    image: `${pressPath}2019/NIT-startup.jpg`,
    alt: "NIT startup platform with Arijit Bhattacharyya mentoring student founders",
    sourceType: "Press Asset",
    tags: ["NIT", "Startup", "Students"],
  },
  {
    id: "raipur-nit",
    title: "NIT Raipur Startup Session",
    outlet: "NIT Raipur",
    publisher: "NIT Raipur",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "2019",
    eyebrow: "University Entrepreneurship",
    summary:
      "NIT Raipur archive asset supporting Arijit's work with student founders, startup platforms and technology education.",
    image: `${pressPath}2019/raipur-NIT.jpg`,
    alt: "NIT Raipur startup session with Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["NIT Raipur", "Startup", "Education"],
  },
  {
    id: "patna-incubation",
    title: "Patna Incubation Platform",
    outlet: "Patna Startup Ecosystem",
    publisher: "Patna Startup Ecosystem",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Startup Incubation",
    summary:
      "Patna incubation archive asset connected to startup mentoring, founder readiness, incubation and regional entrepreneurship development.",
    image: `${pressPath}Patna_Incubation.jpg`,
    alt: "Patna incubation platform with Arijit Bhattacharyya startup mentor",
    sourceType: "Press Asset",
    tags: ["Patna", "Incubation", "Startup"],
  },
  {
    id: "startup-summit",
    title: "Startup Summit",
    outlet: "Startup Summit",
    publisher: "Startup Summit",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Founder Ecosystem",
    summary:
      "Startup Summit archive asset connected to business growth, founder mentoring, venture building and startup ecosystem leadership.",
    image: `${pressPath}startup_summit.jpg`,
    alt: "Startup Summit featuring Arijit Bhattacharyya founder mentor and entrepreneur",
    sourceType: "Press Asset",
    tags: ["Startup Summit", "Founder", "Mentoring"],
  },
  {
    id: "vc-funding",
    title: "VC Funding and Investment Conversations",
    outlet: "Investment Archive",
    publisher: "Investment Archive",
    category: "Event",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Investment Ecosystem",
    summary:
      "Archive item connected to VC funding, investment readiness, founder mentoring and startup capital conversations.",
    image: `${pressPath}vc-funding.jpg`,
    alt: "VC funding and investment conversation with Arijit Bhattacharyya startup mentor",
    sourceType: "Press Asset",
    tags: ["VC Funding", "Investment", "Startup"],
  },
];

export const completeLegacyPressArchive: PressStory[] = [
  ...legacyPressArchive,
  ...additionalLegacyPressArchive,
];

export const technologyPressArchive: PressStory[] = [
  {
    id: "cyber-security-coverage",
    title: "Cyber Security Coverage",
    outlet: "Technology Press Archive",
    publisher: "Technology Press Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Cyber Security",
    summary:
      "Archive asset connected to cyber security, digital risk, technology advisory and Arijit's wider technology leadership positioning.",
    image: `${pressPath}cyber_security.jpg`,
    alt: "Cyber security coverage connected to Arijit Bhattacharyya technology advisor",
    sourceType: "Press Asset",
    tags: ["Cyber Security", "Technology", "Advisory"],
  },
  {
    id: "technology-adviser",
    title: "Technology Adviser Coverage",
    outlet: "Technology Press Archive",
    publisher: "Technology Press Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Technology Advisory",
    summary:
      "Archive item supporting Arijit's positioning as a technology adviser across AI, VR, blockchain, digital systems and business transformation.",
    image: `${pressPath}technology_adviser.jpg`,
    alt: "Technology adviser coverage featuring Arijit Bhattacharyya AI VR and innovation expert",
    sourceType: "Press Asset",
    tags: ["Technology Adviser", "AI", "Innovation"],
  },
  {
    id: "virtual-reality-india",
    title: "Virtual Reality India Coverage",
    outlet: "VR Press Archive",
    publisher: "VR Press Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "VR India",
    summary:
      "Virtual Reality India archive asset supporting legacy SEO and proof around Arijit's early VR, AR, games and immersive technology work.",
    image: `${pressPath}virtual_reality_India.jpg`,
    alt: "Virtual Reality India coverage featuring Arijit Bhattacharyya VR AR game development expert",
    sourceType: "Press Asset",
    tags: ["Virtual Reality India", "VR", "AR"],
  },
  {
    id: "film-virtual-reality",
    title: "Film and Virtual Reality Coverage",
    outlet: "Creative Technology Archive",
    publisher: "Creative Technology Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Film + VR",
    summary:
      "Archive asset connecting film, virtual reality, media technology, digital characters and Arijit's entertainment innovation ecosystem.",
    image: `${pressPath}film_virtual_reality.jpg`,
    alt: "Film and virtual reality coverage connected to Arijit Bhattacharyya immersive media work",
    sourceType: "Press Asset",
    tags: ["Film", "VR", "Media Technology"],
  },
  {
    id: "ai-ml-coverage",
    title: "AI and Machine Learning Coverage",
    outlet: "Latest Speaks Archive",
    publisher: "Latest Speaks Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "AI / ML",
    summary:
      "Archive asset connected to AI, machine learning, automation, intelligent systems and Arijit's future technology speaking work.",
    image: `${latestPath}AI-ML.jpg`,
    alt: "AI and machine learning coverage featuring Arijit Bhattacharyya technology speaker",
    sourceType: "Press Asset",
    tags: ["AI", "Machine Learning", "Future Tech"],
  },
  {
    id: "ai-hr-coverage",
    title: "AI in HR and Workforce Systems",
    outlet: "Latest Speaks Archive",
    publisher: "Latest Speaks Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "AI + HR",
    summary:
      "Archive asset connected to AI in human resources, workforce transformation, automation and digital business operations.",
    image: `${latestPath}AI-HR.jpg`,
    alt: "AI HR coverage featuring Arijit Bhattacharyya on artificial intelligence and workforce transformation",
    sourceType: "Press Asset",
    tags: ["AI HR", "Workforce", "Automation"],
  },
  {
    id: "smart-city-coverage",
    title: "Smart City Technology Coverage",
    outlet: "Latest Speaks Archive",
    publisher: "Latest Speaks Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Smart Cities",
    summary:
      "Smart city archive asset connected to AI, digital infrastructure, IoT, urban innovation and future technology platforms.",
    image: `${latestPath}smart-city.jpg`,
    alt: "Smart city technology coverage connected to Arijit Bhattacharyya AI IoT and innovation work",
    sourceType: "Press Asset",
    tags: ["Smart City", "IoT", "AI"],
  },
  {
    id: "vr-data-science",
    title: "VR and Data Science Coverage",
    outlet: "Latest Speaks Archive",
    publisher: "Latest Speaks Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "VR + Data Science",
    summary:
      "Archive asset connecting virtual reality, data science, analytics and immersive technology learning.",
    image: `${latestPath}vr-data-science.jpg`,
    alt: "VR and data science coverage featuring Arijit Bhattacharyya immersive technology speaker",
    sourceType: "Press Asset",
    tags: ["VR", "Data Science", "Immersive Tech"],
  },
  {
    id: "vr-car",
    title: "VR Car and Immersive Game Coverage",
    outlet: "Latest Speaks Archive",
    publisher: "Latest Speaks Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "VR Games",
    summary:
      "VR car and immersive game archive asset supporting Arijit's early game development, VR and simulation credibility.",
    image: `${latestPath}vr-car.png`,
    alt: "VR car racing game and immersive technology coverage by Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["VR Game", "Simulation", "Gaming"],
  },
  {
    id: "blockchain-mutual-funds",
    title: "Blockchain and Mutual Funds Coverage",
    outlet: "Latest Speaks Archive",
    publisher: "Latest Speaks Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Blockchain Finance",
    summary:
      "Archive asset connecting blockchain, finance, mutual funds, fintech and digital trust conversations.",
    image: `${latestPath}blockchain-mutual-funds.jpg`,
    alt: "Blockchain mutual funds and fintech coverage featuring Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Blockchain", "FinTech", "Finance"],
  },
  {
    id: "crypto-coverage",
    title: "Crypto and Blockchain Coverage",
    outlet: "Latest Speaks Archive",
    publisher: "Latest Speaks Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Crypto / Blockchain",
    summary:
      "Crypto and blockchain archive asset supporting Arijit's blockchain, digital assets, fintech and emerging technology thought leadership.",
    image: `${latestPath}crypto.jpg`,
    alt: "Crypto and blockchain coverage featuring Arijit Bhattacharyya emerging technology speaker",
    sourceType: "Press Asset",
    tags: ["Crypto", "Blockchain", "Digital Assets"],
  },
];

export const creativeMediaArchive: PressStory[] = [
  {
    id: "jeet-boss2",
    title: "Jeet and Boss 2 Game / Entertainment Technology",
    outlet: "Entertainment Media Archive",
    publisher: "Entertainment Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Celebrity + Game IP",
    summary:
      "Archive asset connecting actor Jeet, Boss 2, movie-based game promotion and Arijit's entertainment technology ecosystem.",
    image: `${pressPath}Jeet_Arijit_Bhattacharyya.jpg`,
    alt: "Actor Jeet with Arijit Bhattacharyya during Boss 2 game and entertainment technology promotion",
    sourceType: "Press Asset",
    tags: ["Jeet", "Boss 2", "Game IP"],
  },
  {
    id: "prosenjit-arijit",
    title: "Prosenjit Chatterjee Entertainment Archive",
    outlet: "Entertainment Media Archive",
    publisher: "Entertainment Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Celebrity Media",
    summary:
      "Entertainment archive asset connected to Bengali cinema, celebrity networks, media presence and creative technology.",
    image: `${pressPath}Prosenjit_Chakraborty.jpg`,
    alt: "Prosenjit Chatterjee with Arijit Bhattacharyya in entertainment media archive",
    sourceType: "Press Asset",
    tags: ["Prosenjit", "Cinema", "Entertainment"],
  },
  {
    id: "subhasree-arijit",
    title: "Subhasree Ganguly Game and Media Archive",
    outlet: "Entertainment Media Archive",
    publisher: "Entertainment Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Cinema + Gaming",
    summary:
      "Archive asset connected to movie-led game development, actor-based 3D characters and entertainment technology.",
    image: `${pressPath}Subhasree_Arijit.jpg`,
    alt: "Subhasree Ganguly with Arijit Bhattacharyya for game and entertainment technology work",
    sourceType: "Press Asset",
    tags: ["Subhasree", "Games", "Cinema"],
  },
  {
    id: "paoli-arijit",
    title: "Paoli Dam Entertainment Archive",
    outlet: "Entertainment Media Archive",
    publisher: "Entertainment Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Celebrity Media",
    summary:
      "Entertainment media asset connected to Bengali cinema, celebrity networks and Arijit's creative technology work.",
    image: `${pressPath}Paoli_Arijit.jpg`,
    alt: "Paoli Dam with Arijit Bhattacharyya in entertainment media archive",
    sourceType: "Press Asset",
    tags: ["Paoli Dam", "Cinema", "Media"],
  },
  {
    id: "parambrata-arijit",
    title: "Parambrata Chatterjee Entertainment Archive",
    outlet: "Entertainment Media Archive",
    publisher: "Entertainment Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Cinema Network",
    summary:
      "Archive asset connected to Bengali film ecosystem, media, celebrity collaborations and creative storytelling.",
    image: `${pressPath}Parambrata_Arijit.jpg`,
    alt: "Parambrata Chatterjee with Arijit Bhattacharyya in creative media archive",
    sourceType: "Press Asset",
    tags: ["Parambrata", "Cinema", "Creative"],
  },
  {
    id: "ramoji-films",
    title: "Ramoji Films and Media Ecosystem",
    outlet: "Ramoji Films",
    publisher: "Ramoji Films",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Film Industry",
    summary:
      "Archive asset connected to film industry networks, production ecosystems, media and entertainment technology.",
    image: `${pressPath}Ramoji_Films.jpg`,
    alt: "Ramoji Films media archive connected to Arijit Bhattacharyya entertainment technology work",
    sourceType: "Press Asset",
    tags: ["Ramoji", "Film", "Entertainment"],
  },
  {
    id: "star-wars-archive",
    title: "Star Wars Story and Fan Media Archive",
    outlet: "Creative Media Archive",
    publisher: "Creative Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Pop Culture",
    summary:
      "Archive asset connected to global pop culture, fandom, cosplay, creative storytelling and entertainment technology.",
    image: `${pressPath}Star_Wars_arijit.jpg`,
    alt: "Star Wars themed creative media archive featuring Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Star Wars", "Cosplay", "Pop Culture"],
  },
  {
    id: "cosplay-archive",
    title: "Cosplay and Character Culture",
    outlet: "Creative Media Archive",
    publisher: "Creative Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Cosplay Ecosystem",
    summary:
      "Cosplay archive asset connected to character culture, superhero IP, fan communities and creative entertainment platforms.",
    image: `${pressPath}cosplay.jpg`,
    alt: "Cosplay and character culture archive connected to Arijit Bhattacharyya creative entertainment work",
    sourceType: "Press Asset",
    tags: ["Cosplay", "Characters", "Creative"],
  },
  {
    id: "im-superhero",
    title: "I Am Superhero Creative IP",
    outlet: "Creative Media Archive",
    publisher: "Creative Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Superhero IP",
    summary:
      "Archive asset connected to superhero characters, comics, game worlds and Arijit's original entertainment IP ecosystem.",
    image: `${pressPath}im_superhero.jpg`,
    alt: "I Am Superhero creative IP archive by Arijit Bhattacharyya",
    sourceType: "Press Asset",
    tags: ["Superhero", "Comics", "Game IP"],
  },
  {
    id: "raaz-reboot",
    title: "Raaz Reboot Media Archive",
    outlet: "Entertainment Media Archive",
    publisher: "Entertainment Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Film Media",
    summary:
      "Film media archive asset connected to entertainment coverage, celebrity ecosystem and creative technology positioning.",
    image: `${pressPath}raaz_reboot.jpg`,
    alt: "Raaz Reboot film media archive connected to Arijit Bhattacharyya entertainment work",
    sourceType: "Press Asset",
    tags: ["Film", "Media", "Entertainment"],
  },
  {
    id: "miss-india-archive",
    title: "Miss India / Glamour Media Archive",
    outlet: "Creative Media Archive",
    publisher: "Creative Media Archive",
    category: "Legacy Archive",
    type: "Event",
    region: "India",
    country: "India",
    year: "Legacy",
    eyebrow: "Culture + Media",
    summary:
      "Archive asset connected to fashion, models, media visibility and the wider entertainment ecosystem.",
    image: `${pressPath}miss-india.jpg`,
    alt: "Miss India media archive connected to Arijit Bhattacharyya creative and model ecosystem",
    sourceType: "Press Asset",
    tags: ["Miss India", "Media", "Models"],
  },
];

export const recognitionTimeline: TimelineItem[] = [
  {
    year: "1998",
    title: "Founder Journey Begins",
    outlet: "Virtualinfocom",
    summary:
      "The founder journey began with technology, game development, animation, training and digital IP creation.",
    image: `${latestPath}Arijit-Bhattacharya.jpg`,
    alt: "Arijit Bhattacharyya founder journey since 1998",
  },
  {
    year: "2008+",
    title: "Public Speaking and Founder Mentoring",
    outlet: "National & International Forums",
    summary:
      "Speaking work expanded across entrepreneurship, technology, VR, gaming, fundraising, IP and startup ecosystem conversations.",
    image: `${pressPath}2020/public-speaking.jpg`,
    alt: "Arijit Bhattacharyya public speaking and founder mentoring",
  },
  {
    year: "2018",
    title: "Startup, ICC, IEEE and International Ecosystem Coverage",
    outlet: "ICC / IEEE / Media Archive",
    summary:
      "Legacy archive shows coverage across startup platforms, technology forums, investment sessions and international business networks.",
    image: `${pressPath}2018/IEEE-Ah-ventures.jpg`,
    alt: "IEEE startup and investment coverage with Arijit Bhattacharyya",
  },
  {
    year: "2024",
    title: "Regional and National Press Features",
    outlet: "Anandabazar / Times of India / TV9",
    summary:
      "Recent press archive includes regional and national coverage across Bengali press, Times of India and TV9.",
    image: `${pressPath}2024/timesofindia-s.jpg`,
    alt: "Recent national and regional press features of Arijit Bhattacharyya",
  },
];

export const pressCta = {
  eyebrow: "Media & Speaking Enquiries",
  title: "Looking for an AI speaker, founder interview, startup mentor or technology expert?",
  text:
    "Invite Arijit Bhattacharyya for interviews, keynote sessions, panel discussions, business forums, podcasts, documentary features or media conversations on AI, entrepreneurship, VR, blockchain, gaming, startup capital and global innovation.",
  primaryLabel: "Contact Arijit",
  primaryHref: "/contact",
  secondaryLabel: "Explore Speaking",
  secondaryHref: "/speaking",
};

